config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root  'pages#home'
  get 'about', to: 'pages#about'

  resources :articles

  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  validates :title, presence: true, length: {minimum: 3, maximum: 50}
  validates :description, presence: true, length: {minimum: 10, maximum: 300}
  validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :articles
	before_save { self.email = email.downcase }
	validates :username, presence: true,
		 uniqueness: {case_sensitive: false},
	 	length: {minimum: 3, maximum: 25}
	 	VALID_EMAIL_REGEX= /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i 
	validates :email, presence: true,
		length:{minimum: 5, maximum: 105},
		uniqueness:{case_sensitive: false},
		format: { with: VALID_EMAIL_REGEX }
		has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :update, :show]

  def index
    @articles = Article.all

  end

  def new
  	@article = Article.new
  end

  def edit
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article was updated!"
      redirect_to article_path(@article)
    else 
      render 'edit'
    end
  end

  def create
  	@article = Article.new(article_params)
    @article.user = User.last
  	if @article.save
  		flash[:notice] = "Article was successfully created"
  		redirect_to article_path(@article)
  	else render 'new'
  	end
  end

  def show
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    flash[:notice] = "Article was deleted!"
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description)
  end

end

app/controllers/concerns/sessions_controller.rb
class SessionsController < ApplicationController
	def new
		
	end

	def create
		user = User.find_by(email: params[:session][:email].downcase)
		if user && user.authenticate(params[:session][:password])
			session[:user_id] = user.id
			flash[:success] = "You have logged in successfully"
			redirect_to user_path(user)
		else
			render 'new'
			flash.now[:danger] = "there was something wrong with your ligon info"
		end

	end

	def destroy
		session[:user_id] = nil
		flash[:success] = "You have logged out"
		redirect_to root_path
	end

end

app/controllers/concerns/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			flash[:success] = "Welcome #{@user.username}"
			redirect_to articles_path
		else
			render 'new'
		end
		
	end

	private

	def user_params
		params.require(:user).permit(:username, :email, :password)
	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def home
	end
	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@users = User.all
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			flash[:success] = "Welcome to the blog! #{@user.username}"
			redirect_to articles_path
		else
			render 'new'
		end
	end

	def update
		@user = User.find(params[:id])
		if  @user.update(user_params)
			flash[:success] = "Account updated successfully"
			redirect_to articles_path
		else
			render 'edit'
		end
	end

	def show
		@user = User.find(params[:id])
	end

	def edit
		@user = User.find(params[:id])
	end

	private
	def user_params
		params.require(:user).permit(:username,:email,:password)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def gravatar_for(user, options = {size: 80})
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		size = options[:size]
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
		image_tag(gravatar_url, alt: user.username, class: "img-circle")
	end
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
	<div class="card text-center container">
	  	<div class="card-header">
	    	<h4><%= link_to article.title, article_path(article) %></h4>
		</div>
		<div class="card-body">
		    <h5 class="card-title"><%= truncate(article.description, length:70) %></h5>
		</div>
		<div class="card-footer text-muted">
			<small> By: <%= article.user.username if article.user %>, <%= time_ago_in_words(article.created_at) %> ago. Last updated: <%= time_ago_in_words(article.updated_at) %> ago
		    </small>
		</div>
	</div>
<% end %>	

app/views/articles/_form.html.erb
<div class="form-group">
	<% if @article.errors.any? %>
	<div class="alert alert-danger" role="alert">
		<h3>The following errors occurred</h3>
		<ul>
		  	<% @article.errors.full_messages.each do |msg| %>
		      <li><%= msg %></li>
		    <% end %>
		</ul>
	</div>
	<% end %>

	<%= form_for @article do |f| %>
		<p>
			<%= f.label :title, for:"formGroupExampleInput" %><br/>
			<%= f.text_field :title, type:"text", class:"form-control", id:"formGroupExampleInput", placeholder:"Title" %>
		</p>
		<p>
			<%= f.label :description, for:"exampleFormControlTextarea1" %><br/>
			<%= f.text_area :description, class:"form-control", id:"exampleFormControlTextarea1", rows:"3" %>
		</p>
		<p>
			<%= f.submit %> <%=  link_to "Back to listing", articles_path,  type: "button", class: "btn btn-default" %>

		</p>
	<% end %>
</div>

app/views/articles/edit.html.erb
<div class="page-header">
  <h1>Edit your post</h1>
</div>

<%= render 'form' %>

app/views/articles/index.html.erb
<div class="page-header">
  <h1 align="center">Articles</h1>
  <p align="center" >Create, edit and view</p>
  <p align="center"><%= link_to " New article", new_article_path,type: "button", class: "btn btn-default" %></p>
</div>

<%= render 'article', obj: @articles %>

app/views/articles/new.html.erb
<div class="page-header">
  <h1>New post</h1>
</div>
<%= render 'form' %>

app/views/articles/show.html.erb
<div class="page-header">
  <h1><%= @article.title %></h1>
</div>

<div class="panel panel-default">
  <div class="panel-body">
    <p><%= @article.description %></p>
  </div>
</div>

<div  class="btn-group" role="group" aria-label="Basic example">
	
	<%=  link_to "Back to listing", articles_path, type: "button", class: "btn btn-default" %> 
	<%=  link_to "Edit this", edit_article_path(@article), type: "button", class: "btn btn-default" %>
	<%= button_to "Delete", article_path(@article), method: :delete, type: "button", class: "btn btn-default showbtn", data: { confirm: "Are you sure you want to delete?" } %>	
</div> 

<h3>Created by:</h3>
<div class="user-card">

	<div class="user-card-body">
		<div class="username"> <%= link_to gravatar_for(@article.user), user_path(@article.user) %>  <%= link_to @article.user.username, user_path(@article.user)%></div>
		</div>
	<div class="article-count"><%= pluralize(@article.user.articles.count, "article") if @article.user.articles %></div>
</div>

app/views/layouts/_footer.html.erb
<div class="container">
	<footer class="footer">
		<small>
			Copyright &copy; <a href="httpd://www.udemy.com"> Udemy course</a>

		</small>
		
	</footer>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
<div class="alert alert-info container" role="alert" >
	<p><%= msg %></p>		
</div>
	
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Alpha Blog", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to "About", about_path, id: "navbar-button"%>
        </li>
        <li><%= link_to "Articles", articles_path, id:"navbar-button"%></li>
        <li> <%= link_to "Log Out", logout_path, method: :destroy, id: "navbar-button" %></li>
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
        <li>
          <form class="navbar-form navbar-left">

            <div class="form-group">
             
            </div>
          </form>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation'%>
    <%= render 'layouts/messages' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="center jumbotron">
		  <h1>About</h1>
		</div>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html>
	<head>
		
	</head>
	<body>
		<div class="center jumbotron">
		  <h1>Hello! Welcome to the home page</h1>
		  <p><%= link_to "Sign up", signup_path , class: "btn btn-primary btn-lg" %>  <%= link_to "Log in", login_path , class: "btn btn-primary btn-lg" %> </p>
		</div>
	</body>
</html>

app/views/users/_form.html.erb
<div class="form-group">
	<% if @user.errors.any? %>
	<div class="alert alert-danger" role="alert">
		<h3>The following errors occurred</h3>
		<ul>
		  	<% @user.errors.full_messages.each do |msg| %>
		      <li><%= msg %></li>
		    <% end %>
		</ul>
	</div>
	<% end %>

	<%= form_for @user do |f| %>
		<p>
			<%= f.label :username, for:"formGroupExampleInput" %><br/>
			<%= f.text_field :username, type:"text", class:"form-control", id:"formGroupExampleInput", placeholder:"Enter username" %>
		</p>
		<p>
			<%= f.label :email, for:"exampleFormControlTextarea1" %><br/>
			<%= f.email_field :email, class:"form-control", id:"exampleFormControlTextarea1", placeholder:"Enter email" %>
		</p>
		<p>
			<%= f.label :password, for:"exampleFormControlTextarea1" %><br/>
			<%= f.password_field :password, class:"form-control", id:"exampleFormControlTextarea1", placeholder:"Enter password" %>
		</p>
		<p>
			<%= f.submit (@user.new_record? ? "Signup" : "Update Account") %> <%=  link_to "Back to listing", articles_path,  type: "button", class: "btn btn-default" %>

		</p>
	<% end %>
</div>

app/views/users/edit.html.erb
<h1>Edit You Account</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1 class="titles">All Alpha Bloggers</h1>
<% @users.each do |user| %>
		<div class="user-card">
			<div class="user-card-body">
				<div class="username"> <%= link_to gravatar_for(user), user_path(user) %>  <%= link_to user.username, user_path(user)%></div>
			</div>
			<div class="article-count"><%= pluralize(user.articles.count, "article") if user.articles %></div>
		</div>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<div class= "username" align="center"><h2><%= @user.username%></h2></div>
<div class = "profilepic" align="center">
	<%= gravatar_for @user, size: 150 %>
</div>

<div align="center">
	<h4 class="titles"> <%= @user.username%>'s articles</h4>
</div>
<%= render 'articles/article', obj: @user.articles %>